/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './_layouts/**/*.html',
    './_includes/**/*.html',
    './*.html',
    './*.md',
    './_books/**/*.md',
    './_posts/**/*.md',
    './assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#b80049',
        'on-primary': '#ffffff',
        'primary-container': '#e2165f',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffd9de',
        'primary-fixed-dim': '#ffb2be',
        'on-primary-fixed': '#400014',
        'on-primary-fixed-variant': '#900038',
        'inverse-primary': '#ffb2be',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        tertiary: '#006769',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#008284',
        'on-tertiary-container': '#f3ffff',
        'tertiary-fixed': '#7bf5f8',
        'tertiary-fixed-dim': '#5cd8db',
        'on-tertiary-fixed': '#002021',
        'on-tertiary-fixed-variant': '#004f51',
        surface: '#fbf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e2',
        'surface-variant': '#e3e2e2',
        'surface-tint': '#bc004b',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#5b3f43',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#8f6f73',
        'outline-variant': '#e4bdc2',
        background: '#fbf9f9',
        'on-background': '#1b1c1c',
        'background-dark': '#121212',
        'surface-light': '#f8f9fa',
        accent: '#0d9488',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        headline: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        serif: ['Montserrat', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1120px',
        'section-gap-md': '64px',
        'section-gap-lg': '80px',
      },
      maxWidth: {
        container: '1120px',
        'container-wide': '1280px',
      },
      boxShadow: {
        cozy: '0 10px 30px -5px rgba(184, 0, 73, 0.05)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ],
};